services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  logs:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: logs_service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/logs
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
